import com.bluelinelabs.logansquare.LoganSquare;
import com.bluelinelabs.logansquare.typeconverters.TypeConverter;
import com.twitter.api.model.json.liveevent.JsonBroadcast$a;
import com.twitter.api.model.json.liveevent.JsonBroadcast;
import tv.periscope.model.b;
import com.twitter.api.model.json.timeline.urt.JsonTimelineRichFeedbackBehaviorMuteUser;
import com.twitter.api.model.json.timeline.urt.JsonTimelineRichFeedbackBehaviorReportTweet;
import com.twitter.api.model.json.timeline.urt.JsonTimelineRichFeedbackBehaviorReportList;
import com.twitter.api.model.json.timeline.urt.JsonTimelineRichFeedbackBehaviorBlockUser;
import com.twitter.api.model.json.reactions.JsonGraphQlTweetReactionTypeMap;
import com.twitter.api.model.json.reactions.JsonTweetReactionTimelineResponse;
import com.twitter.api.model.json.reactions.JsonTweetReactionTimelineEntry;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonTweetData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonToggleWrapperData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonStaticTextData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonSpacerData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonProgressIndicatorData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonListData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonInfoItemData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonImageData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonGroupSettingsData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonCardWrapperData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonButtonData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonButtonItemData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonBooleanData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonAlertExampleData;
import com.twitter.api.model.json.onboarding.JsonSettingsValue$JsonActionData;
import com.twitter.api.model.json.media.sticker.JsonStickerCatalogResponse;
import com.twitter.api.model.json.edit.JsonPreviousCounts;
import com.twitter.api.model.json.core.JsonConversationControl;
import com.twitter.api.model.json.core.JsonApiTweet;
import com.twitter.api.model.json.card.JsonPollCompose;
import com.twitter.api.model.json.geo.JsonPlacePageResponse;
import com.twitter.api.model.json.common.JsonTwitterErrors;
import com.twitter.api.model.json.common.JsonTwitterError;
import com.twitter.api.model.json.account.JsonOauthRequestTokenResponse;
import com.twitter.api.model.json.account.JsonOauthPermissionPolicy;
import com.twitter.api.model.json.account.JsonOauthPermission;
import com.twitter.api.model.json.account.JsonGuestToken;
import com.twitter.api.model.json.account.JsonAccessToken;
import com.twitter.model.json.common.JsonModelRegistry$a;
import com.twitter.model.json.common.JsonModelRegistry$b;
import com.twitter.model.json.common.JsonModelRegistry$Registrar;

// 
// Decompiled by Procyon v0.6.0
// 

public final class c2v implements JsonModelRegistry$Registrar
{
    public final void a(final JsonModelRegistry$b jsonModelRegistry$b) {
        final JsonModelRegistry$a jsonModelRegistry$a = (JsonModelRegistry$a)jsonModelRegistry$b;
        jsonModelRegistry$a.b((Class)mf.class, (Class)JsonAccessToken.class, (ypa)null);
        jsonModelRegistry$a.b((Class)l9c.class, (Class)JsonGuestToken.class, (ypa)null);
        jsonModelRegistry$a.b((Class)j3j.class, (Class)JsonOauthPermission.class, (ypa)null);
        jsonModelRegistry$a.b((Class)k3j.class, (Class)JsonOauthPermissionPolicy.class, (ypa)null);
        jsonModelRegistry$a.b((Class)l3j.class, (Class)JsonOauthRequestTokenResponse.class, (ypa)null);
        jsonModelRegistry$a.b((Class)hbv.class, (Class)JsonTwitterError.class, (ypa)n1x.f);
        jsonModelRegistry$a.b((Class)kbv.class, (Class)JsonTwitterErrors.class, (ypa)null);
        jsonModelRegistry$a.b((Class)sev.class, (Class)JsonPlacePageResponse.class, (ypa)null);
        jsonModelRegistry$a.b((Class)sev$a.class, (Class)JsonPlacePageResponse.JsonPlacePageHeader.class, (ypa)null);
        jsonModelRegistry$a.b((Class)sev$b.class, (Class)JsonPlacePageResponse.JsonPlacePageTimeline.class, (ypa)null);
        jsonModelRegistry$a.b((Class)wpk.class, (Class)JsonPollCompose.class, (ypa)null);
        jsonModelRegistry$a.b((Class)nh0.class, (Class)JsonApiTweet.class, (ypa)null);
        jsonModelRegistry$a.a((Class)nh0$a.class, (Class)JsonApiTweet.class);
        jsonModelRegistry$a.b((Class)iq6.class, (Class)JsonConversationControl.class, (ypa)null);
        jsonModelRegistry$a.a((Class)iq6$a.class, (Class)JsonConversationControl.class);
        jsonModelRegistry$a.b((Class)iyk.class, (Class)JsonPreviousCounts.class, (ypa)null);
        jsonModelRegistry$a.b((Class)sgr.class, (Class)JsonStickerCatalogResponse.class, (ypa)null);
        jsonModelRegistry$a.b((Class)zk.class, (Class)JsonSettingsValue$JsonActionData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)zk.b.class, (Class)JsonSettingsValue$JsonActionData.class);
        jsonModelRegistry$a.b((Class)yw.class, (Class)JsonSettingsValue$JsonAlertExampleData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)yw$b.class, (Class)JsonSettingsValue$JsonAlertExampleData.class);
        jsonModelRegistry$a.b((Class)g72.class, (Class)JsonSettingsValue$JsonBooleanData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)g72.b.class, (Class)JsonSettingsValue$JsonBooleanData.class);
        jsonModelRegistry$a.b((Class)r43.class, (Class)JsonSettingsValue$JsonButtonItemData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)r43$a.class, (Class)JsonSettingsValue$JsonButtonItemData.class);
        jsonModelRegistry$a.b((Class)z43.class, (Class)JsonSettingsValue$JsonButtonData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)z43.a.class, (Class)JsonSettingsValue$JsonButtonData.class);
        jsonModelRegistry$a.b((Class)ki3.class, (Class)JsonSettingsValue$JsonCardWrapperData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)ki3$a.class, (Class)JsonSettingsValue$JsonCardWrapperData.class);
        jsonModelRegistry$a.b((Class)i8c.class, (Class)JsonSettingsValue$JsonGroupSettingsData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)i8c.a.class, (Class)JsonSettingsValue$JsonGroupSettingsData.class);
        jsonModelRegistry$a.b((Class)f8d.class, (Class)JsonSettingsValue$JsonImageData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)f8d$a.class, (Class)JsonSettingsValue$JsonImageData.class);
        jsonModelRegistry$a.b((Class)tld.class, (Class)JsonSettingsValue$JsonInfoItemData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)tld$a.class, (Class)JsonSettingsValue$JsonInfoItemData.class);
        jsonModelRegistry$a.b((Class)vlf.class, (Class)JsonSettingsValue$JsonListData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)vlf$a.class, (Class)JsonSettingsValue$JsonListData.class);
        jsonModelRegistry$a.b((Class)rhl.class, (Class)JsonSettingsValue$JsonProgressIndicatorData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)rhl$a.class, (Class)JsonSettingsValue$JsonProgressIndicatorData.class);
        jsonModelRegistry$a.b((Class)wqp.class, (Class)JsonSettingsValue.class, (ypa)null);
        jsonModelRegistry$a.b((Class)hoq.class, (Class)JsonSettingsValue$JsonSpacerData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)hoq.a.class, (Class)JsonSettingsValue$JsonSpacerData.class);
        jsonModelRegistry$a.b((Class)par.class, (Class)JsonSettingsValue$JsonStaticTextData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)par.a.class, (Class)JsonSettingsValue$JsonStaticTextData.class);
        jsonModelRegistry$a.b((Class)igt.class, (Class)JsonSettingsValue$JsonToggleWrapperData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)igt.a.class, (Class)JsonSettingsValue$JsonToggleWrapperData.class);
        jsonModelRegistry$a.b((Class)rsu.class, (Class)JsonSettingsValue$JsonTweetData.class, (ypa)null);
        jsonModelRegistry$a.a((Class)rsu$a.class, (Class)JsonSettingsValue$JsonTweetData.class);
        jsonModelRegistry$a.b((Class)xou.class, (Class)JsonTweetReactionTimelineEntry.class, (ypa)null);
        jsonModelRegistry$a.b((Class)hpu.class, (Class)JsonTweetReactionTimelineResponse.class, (ypa)null);
        jsonModelRegistry$a.b((Class)mpu.class, (Class)JsonGraphQlTweetReactionTypeMap.class, (ypa)null);
        jsonModelRegistry$a.b((Class)w2t.class, (Class)JsonTimelineRichFeedbackBehaviorBlockUser.class, (ypa)null);
        jsonModelRegistry$a.a((Class)w2t$a.class, (Class)JsonTimelineRichFeedbackBehaviorBlockUser.class);
        jsonModelRegistry$a.b((Class)z2t.class, (Class)JsonTimelineRichFeedbackBehaviorReportList.class, (ypa)null);
        jsonModelRegistry$a.a((Class)z2t$a.class, (Class)JsonTimelineRichFeedbackBehaviorReportList.class);
        jsonModelRegistry$a.b((Class)a3t.class, (Class)JsonTimelineRichFeedbackBehaviorReportTweet.class, (ypa)null);
        jsonModelRegistry$a.a((Class)a3t$a.class, (Class)JsonTimelineRichFeedbackBehaviorReportTweet.class);
        jsonModelRegistry$a.b((Class)d3t.class, (Class)JsonTimelineRichFeedbackBehaviorMuteUser.class, (ypa)null);
        jsonModelRegistry$a.a((Class)d3t$a.class, (Class)JsonTimelineRichFeedbackBehaviorMuteUser.class);
        jsonModelRegistry$a.b((Class)b.class, (Class)JsonBroadcast.class, (ypa)null);
        jsonModelRegistry$a.a((Class)JsonBroadcast$a.class, (Class)JsonBroadcast.class);
        jsonModelRegistry$a.c((Class)h10.class, (TypeConverter)new lce());
        jsonModelRegistry$a.c((Class)wke.class, (TypeConverter)new xke());
        jsonModelRegistry$a.c((Class)a1u.class, (TypeConverter)new yie());
        jsonModelRegistry$a.c((Class)cgv$b.class, (TypeConverter)new com.twitter.api.model.json.core.b());
        final com.twitter.api.model.json.core.b b = new com.twitter.api.model.json.core.b();
        final vee a = gih.a;
        LoganSquare.registerTypeConverter((Class)cgv.class, (TypeConverter)new hih((TypeConverter)b));
        jsonModelRegistry$a.c((Class)qq9.class, (TypeConverter)new xq9());
        jsonModelRegistry$a.c((Class)tbf.class, (TypeConverter)new wbf());
        jsonModelRegistry$a.c((Class)ozl.class, (TypeConverter)new lhe());
    }
}
