// 
// Decompiled by Procyon v0.6.0
// 

public final class wlq extends gr1
{
    public wlq() {
        super.b.b("intent", "favorite", 1001);
        super.b.b("intent", "like", 1001);
        super.b.b("intent", "follow", 1002);
        super.b.b("intent", "retweet", 1003);
        super.b.b("account", (String)null, 1004);
        super.b.b("articles", (String)null, 1004);
        super.b.b("badge_violations", (String)null, 1004);
        super.b.b("follow", (String)null, 1002);
        super.b.b("unfollow", (String)null, 1002);
        super.b.b("moments", (String)null, 1004);
        super.b.b("profile_spotlight", (String)null, 1004);
        super.b.b("moments", "guide", 1004);
        super.b.b("notes", "*", 1004);
        super.b.b("profiles", "edit", 1004);
        super.b.b("profiles", "edit/birthday", 1004);
        super.b.b("settings", "account", 1004);
        super.b.b("settings", "backup_code", 1004);
        super.b.b("settings", "connected_apps", 1004);
        super.b.b("settings", "devices", 1004);
        super.b.b("settings", "email_notifications", 1004);
        super.b.b("settings", "login_verification", 1004);
        super.b.b("settings", "password", 1004);
        super.b.b("settings", "personalization", 1004);
        super.b.b("settings", "your_twitter_data", 1004);
        super.b.b("settings", "safety_mode", 1004);
        super.b.b("settings", "safety_mode/*", 1004);
        super.b.b("settings", "safety_mode/*/*", 1004);
        super.b.b("live", "timeline/*", 1004);
        super.b.b("subscriptions", "*", 1004);
        super.b.b("subscriptions", "*/*", 1004);
        super.a.c("settings/ads_preferences", 1004);
        super.a.c("i/notes/*", 1004);
        super.a.c("i/articles", 1004);
        super.a.c("i/birdwatch/n/*", 1004);
        super.a.c("i/birdwatch/t/*", 1004);
        super.a.c("i/birdwatch/u/*", 1004);
        super.a.c("i/communities/*", 1004);
        super.a.c("i/communities/*/about", 1004);
        super.a.c("i/communities/*/rules", 1004);
        super.a.c("i/communities/*/rules", 1004);
        super.a.c("i/communities/*/moderation/reported_tweets", 1004);
        super.a.c("i/custom-timelines/*/info", 1004);
        super.a.c("digest/*", 1004);
        super.a.c("/follower_requests", 1004);
        super.a.c("i/tfb/v1/quick_promote/android/*", 1004);
        super.a.c("i/tweet_notifications_timeline", 1004);
        super.a.c("i/notifications", 1004);
        super.a.c("i/verified_followers", 1004);
        super.a.c("i/direct_messages", 1004);
        super.a.c("i/connect", 1004);
        super.a.c("i/connect_people", 1004);
        super.a.c("who_to_follow", 1004);
        super.a.c("who_to_follow/*", 1004);
        super.a.c("people_timeline", 1004);
        super.a.c("favorites", 1004);
        super.a.c("likes", 1004);
        super.a.c("professionals/contact_sheet", 1004);
        super.a.c("i/safety_center", 1004);
        super.a.c("i/safety_center/reports/*", 1004);
        super.a.c("i/safety_center/reports/*/more", 1004);
        super.a.c("i/safety_center/*", 1004);
        super.a.c("i/reports/*", 1004);
        super.a.c("i/safety_mode", 1004);
        super.a.c("i/safety_mode/actioned_tweets/*", 1004);
        super.a.c("i/safety_mode/flagged_accounts", 1004);
        super.a.c("i/safety_mode/flagged_tweets/*", 1004);
        super.a.c("i/safety/report_story_start", 1004);
        super.a.c("settings/safety_mode", 1004);
        super.a.c("settings/safety_mode/autoblocked", 1004);
        super.a.c("settings/safety_mode/flagged_tweets/*", 1004);
        super.a.c("settings/ads_preferences", 1004);
        super.a.c("settings/applications", 1004);
        super.a.c("settings/audience_and_tagging", 1004);
        super.a.c("settings/blocked/all", 1004);
        super.a.c("settings/device_follow", 1004);
        super.a.c("settings/direct_messages", 1004);
        super.a.c("settings/email_notifications", 1004);
        super.a.c("settings/languages", 1004);
        super.a.c("settings/location_information", 1004);
        super.a.c("settings/monetization", 1004);
        super.a.c("settings/mute", 1004);
        super.a.c("settings/notifications/advanced_filters", 1004);
        super.a.c("settings/password", 1004);
        super.a.c("settings/personalization", 1004);
        super.a.c("settings/professional_profile/profile_spotlight", 1004);
        super.a.c("settings/professional_profile/profile_spotlight/shop", 1004);
        super.a.c("settings/profile", 1004);
        super.a.c("settings/replies", 1004);
        super.a.c("settings/security", 1004);
        super.a.c("settings/sessions", 1004);
        super.a.c("settings/your_twitter_data", 1004);
        super.a.c("i/shopping/drop/*", 1004);
        super.a.c("i/twitter_blue_sign_up", 1004);
        super.a.c("settings/twitter_blue", 1004);
        super.a.c("settings/superfollows", 1004);
        super.a.c("superfollows/error", 1004);
        super.a.c("superfollows/*/error", 1004);
        super.a.c("i/topics/picker/*", 1004);
        super.a.c("i/badge_violations", 1004);
        super.a.c("lists", 1004);
        super.a.c("find_friends", 1004);
        super.a.c("turn_on_push", 1004);
        super.a.c("intent/tweet", 1004);
        super.a.c("intent/retweet", 1004);
        super.a.c("intent/favorite", 1004);
        super.a.c("intent/like", 1004);
        super.a.c("intent/follow", 1004);
        super.a.c("live/timeline/*", 1004);
        super.a.c("*/status/*/analytics", 1004);
    }
}
