import java.io.IOException;
import java.util.HashMap;

// 
// Decompiled by Procyon v0.6.0
// 

public final class z6z implements b5j<uhz>
{
    public static final lxa A;
    public static final lxa B;
    public static final lxa C;
    public static final lxa D;
    public static final lxa E;
    public static final lxa F;
    public static final lxa G;
    public static final lxa H;
    public static final lxa I;
    public static final lxa J;
    public static final lxa K;
    public static final lxa L;
    public static final lxa M;
    public static final lxa N;
    public static final lxa O;
    public static final lxa P;
    public static final lxa Q;
    public static final lxa R;
    public static final lxa S;
    public static final lxa T;
    public static final lxa U;
    public static final lxa V;
    public static final lxa W;
    public static final lxa X;
    public static final lxa Y;
    public static final lxa Z;
    public static final z6z a;
    public static final lxa a0;
    public static final lxa b;
    public static final lxa b0;
    public static final lxa c;
    public static final lxa c0;
    public static final lxa d;
    public static final lxa d0;
    public static final lxa e;
    public static final lxa e0;
    public static final lxa f;
    public static final lxa f0;
    public static final lxa g;
    public static final lxa g0;
    public static final lxa h;
    public static final lxa i;
    public static final lxa j;
    public static final lxa k;
    public static final lxa l;
    public static final lxa m;
    public static final lxa n;
    public static final lxa o;
    public static final lxa p;
    public static final lxa q;
    public static final lxa r;
    public static final lxa s;
    public static final lxa t;
    public static final lxa u;
    public static final lxa v;
    public static final lxa w;
    public static final lxa x;
    public static final lxa y;
    public static final lxa z;
    
    static {
        final vry f2 = vry.F0;
        a = new z6z();
        final cry cry = new cry(1, f2);
        final HashMap hashMap = new HashMap();
        hashMap.put(cry.annotationType(), cry);
        b = new lxa("systemInfo", wa0.A(hashMap), null);
        final cry cry2 = new cry(2, f2);
        final HashMap hashMap2 = new HashMap();
        hashMap2.put(cry2.annotationType(), cry2);
        c = new lxa("eventName", wa0.A(hashMap2), null);
        final cry cry3 = new cry(37, f2);
        final HashMap hashMap3 = new HashMap();
        hashMap3.put(cry3.annotationType(), cry3);
        d = new lxa("isThickClient", wa0.A(hashMap3), null);
        final cry cry4 = new cry(61, f2);
        final HashMap hashMap4 = new HashMap();
        hashMap4.put(cry4.annotationType(), cry4);
        e = new lxa("clientType", wa0.A(hashMap4), null);
        final cry cry5 = new cry(3, f2);
        final HashMap hashMap5 = new HashMap();
        hashMap5.put(cry5.annotationType(), cry5);
        f = new lxa("modelDownloadLogEvent", wa0.A(hashMap5), null);
        final cry cry6 = new cry(20, f2);
        final HashMap hashMap6 = new HashMap();
        hashMap6.put(cry6.annotationType(), cry6);
        g = new lxa("customModelLoadLogEvent", wa0.A(hashMap6), null);
        final cry cry7 = new cry(4, f2);
        final HashMap hashMap7 = new HashMap();
        hashMap7.put(cry7.annotationType(), cry7);
        h = new lxa("customModelInferenceLogEvent", wa0.A(hashMap7), null);
        final cry cry8 = new cry(29, f2);
        final HashMap hashMap8 = new HashMap();
        hashMap8.put(cry8.annotationType(), cry8);
        i = new lxa("customModelCreateLogEvent", wa0.A(hashMap8), null);
        final cry cry9 = new cry(5, f2);
        final HashMap hashMap9 = new HashMap();
        hashMap9.put(cry9.annotationType(), cry9);
        j = new lxa("onDeviceFaceDetectionLogEvent", wa0.A(hashMap9), null);
        final cry cry10 = new cry(59, f2);
        final HashMap hashMap10 = new HashMap();
        hashMap10.put(cry10.annotationType(), cry10);
        k = new lxa("onDeviceFaceLoadLogEvent", wa0.A(hashMap10), null);
        final cry cry11 = new cry(6, f2);
        final HashMap hashMap11 = new HashMap();
        hashMap11.put(cry11.annotationType(), cry11);
        l = new lxa("onDeviceTextDetectionLogEvent", wa0.A(hashMap11), null);
        final cry cry12 = new cry(7, f2);
        final HashMap hashMap12 = new HashMap();
        hashMap12.put(cry12.annotationType(), cry12);
        m = new lxa("onDeviceBarcodeDetectionLogEvent", wa0.A(hashMap12), null);
        final cry cry13 = new cry(58, f2);
        final HashMap hashMap13 = new HashMap();
        hashMap13.put(cry13.annotationType(), cry13);
        n = new lxa("onDeviceBarcodeLoadLogEvent", wa0.A(hashMap13), null);
        final cry cry14 = new cry(48, f2);
        final HashMap hashMap14 = new HashMap();
        hashMap14.put(cry14.annotationType(), cry14);
        o = new lxa("onDeviceImageLabelCreateLogEvent", wa0.A(hashMap14), null);
        final cry cry15 = new cry(49, f2);
        final HashMap hashMap15 = new HashMap();
        hashMap15.put(cry15.annotationType(), cry15);
        p = new lxa("onDeviceImageLabelLoadLogEvent", wa0.A(hashMap15), null);
        final cry cry16 = new cry(18, f2);
        final HashMap hashMap16 = new HashMap();
        hashMap16.put(cry16.annotationType(), cry16);
        q = new lxa("onDeviceImageLabelDetectionLogEvent", wa0.A(hashMap16), null);
        final cry cry17 = new cry(26, f2);
        final HashMap hashMap17 = new HashMap();
        hashMap17.put(cry17.annotationType(), cry17);
        r = new lxa("onDeviceObjectCreateLogEvent", wa0.A(hashMap17), null);
        final cry cry18 = new cry(27, f2);
        final HashMap hashMap18 = new HashMap();
        hashMap18.put(cry18.annotationType(), cry18);
        s = new lxa("onDeviceObjectLoadLogEvent", wa0.A(hashMap18), null);
        final cry cry19 = new cry(28, f2);
        final HashMap hashMap19 = new HashMap();
        hashMap19.put(cry19.annotationType(), cry19);
        t = new lxa("onDeviceObjectInferenceLogEvent", wa0.A(hashMap19), null);
        final cry cry20 = new cry(44, f2);
        final HashMap hashMap20 = new HashMap();
        hashMap20.put(cry20.annotationType(), cry20);
        u = new lxa("onDevicePoseDetectionLogEvent", wa0.A(hashMap20), null);
        final cry cry21 = new cry(45, f2);
        final HashMap hashMap21 = new HashMap();
        hashMap21.put(cry21.annotationType(), cry21);
        v = new lxa("onDeviceSegmentationLogEvent", wa0.A(hashMap21), null);
        final cry cry22 = new cry(19, f2);
        final HashMap hashMap22 = new HashMap();
        hashMap22.put(cry22.annotationType(), cry22);
        w = new lxa("onDeviceSmartReplyLogEvent", wa0.A(hashMap22), null);
        final cry cry23 = new cry(21, f2);
        final HashMap hashMap23 = new HashMap();
        hashMap23.put(cry23.annotationType(), cry23);
        x = new lxa("onDeviceLanguageIdentificationLogEvent", wa0.A(hashMap23), null);
        final cry cry24 = new cry(22, f2);
        final HashMap hashMap24 = new HashMap();
        hashMap24.put(cry24.annotationType(), cry24);
        y = new lxa("onDeviceTranslationLogEvent", wa0.A(hashMap24), null);
        final cry cry25 = new cry(8, f2);
        final HashMap hashMap25 = new HashMap();
        hashMap25.put(cry25.annotationType(), cry25);
        z = new lxa("cloudFaceDetectionLogEvent", wa0.A(hashMap25), null);
        final cry cry26 = new cry(9, f2);
        final HashMap hashMap26 = new HashMap();
        hashMap26.put(cry26.annotationType(), cry26);
        A = new lxa("cloudCropHintDetectionLogEvent", wa0.A(hashMap26), null);
        final cry cry27 = new cry(10, f2);
        final HashMap hashMap27 = new HashMap();
        hashMap27.put(cry27.annotationType(), cry27);
        B = new lxa("cloudDocumentTextDetectionLogEvent", wa0.A(hashMap27), null);
        final cry cry28 = new cry(11, f2);
        final HashMap hashMap28 = new HashMap();
        hashMap28.put(cry28.annotationType(), cry28);
        C = new lxa("cloudImagePropertiesDetectionLogEvent", wa0.A(hashMap28), null);
        final cry cry29 = new cry(12, f2);
        final HashMap hashMap29 = new HashMap();
        hashMap29.put(cry29.annotationType(), cry29);
        D = new lxa("cloudImageLabelDetectionLogEvent", wa0.A(hashMap29), null);
        final cry cry30 = new cry(13, f2);
        final HashMap hashMap30 = new HashMap();
        hashMap30.put(cry30.annotationType(), cry30);
        E = new lxa("cloudLandmarkDetectionLogEvent", wa0.A(hashMap30), null);
        final cry cry31 = new cry(14, f2);
        final HashMap hashMap31 = new HashMap();
        hashMap31.put(cry31.annotationType(), cry31);
        F = new lxa("cloudLogoDetectionLogEvent", wa0.A(hashMap31), null);
        final cry cry32 = new cry(15, f2);
        final HashMap hashMap32 = new HashMap();
        hashMap32.put(cry32.annotationType(), cry32);
        G = new lxa("cloudSafeSearchDetectionLogEvent", wa0.A(hashMap32), null);
        final cry cry33 = new cry(16, f2);
        final HashMap hashMap33 = new HashMap();
        hashMap33.put(cry33.annotationType(), cry33);
        H = new lxa("cloudTextDetectionLogEvent", wa0.A(hashMap33), null);
        final cry cry34 = new cry(17, f2);
        final HashMap hashMap34 = new HashMap();
        hashMap34.put(cry34.annotationType(), cry34);
        I = new lxa("cloudWebSearchDetectionLogEvent", wa0.A(hashMap34), null);
        final cry cry35 = new cry(23, f2);
        final HashMap hashMap35 = new HashMap();
        hashMap35.put(cry35.annotationType(), cry35);
        J = new lxa("automlImageLabelingCreateLogEvent", wa0.A(hashMap35), null);
        final cry cry36 = new cry(24, f2);
        final HashMap hashMap36 = new HashMap();
        hashMap36.put(cry36.annotationType(), cry36);
        K = new lxa("automlImageLabelingLoadLogEvent", wa0.A(hashMap36), null);
        final cry cry37 = new cry(25, f2);
        final HashMap hashMap37 = new HashMap();
        hashMap37.put(cry37.annotationType(), cry37);
        L = new lxa("automlImageLabelingInferenceLogEvent", wa0.A(hashMap37), null);
        final cry cry38 = new cry(39, f2);
        final HashMap hashMap38 = new HashMap();
        hashMap38.put(cry38.annotationType(), cry38);
        M = new lxa("isModelDownloadedLogEvent", wa0.A(hashMap38), null);
        final cry cry39 = new cry(40, f2);
        final HashMap hashMap39 = new HashMap();
        hashMap39.put(cry39.annotationType(), cry39);
        N = new lxa("deleteModelLogEvent", wa0.A(hashMap39), null);
        final cry cry40 = new cry(30, f2);
        final HashMap hashMap40 = new HashMap();
        hashMap40.put(cry40.annotationType(), cry40);
        O = new lxa("aggregatedAutomlImageLabelingInferenceLogEvent", wa0.A(hashMap40), null);
        final cry cry41 = new cry(31, f2);
        final HashMap hashMap41 = new HashMap();
        hashMap41.put(cry41.annotationType(), cry41);
        P = new lxa("aggregatedCustomModelInferenceLogEvent", wa0.A(hashMap41), null);
        final cry cry42 = new cry(32, f2);
        final HashMap hashMap42 = new HashMap();
        hashMap42.put(cry42.annotationType(), cry42);
        Q = new lxa("aggregatedOnDeviceFaceDetectionLogEvent", wa0.A(hashMap42), null);
        final cry cry43 = new cry(33, f2);
        final HashMap hashMap43 = new HashMap();
        hashMap43.put(cry43.annotationType(), cry43);
        R = new lxa("aggregatedOnDeviceBarcodeDetectionLogEvent", wa0.A(hashMap43), null);
        final cry cry44 = new cry(34, f2);
        final HashMap hashMap44 = new HashMap();
        hashMap44.put(cry44.annotationType(), cry44);
        S = new lxa("aggregatedOnDeviceImageLabelDetectionLogEvent", wa0.A(hashMap44), null);
        final cry cry45 = new cry(35, f2);
        final HashMap hashMap45 = new HashMap();
        hashMap45.put(cry45.annotationType(), cry45);
        T = new lxa("aggregatedOnDeviceObjectInferenceLogEvent", wa0.A(hashMap45), null);
        final cry cry46 = new cry(36, f2);
        final HashMap hashMap46 = new HashMap();
        hashMap46.put(cry46.annotationType(), cry46);
        U = new lxa("aggregatedOnDeviceTextDetectionLogEvent", wa0.A(hashMap46), null);
        final cry cry47 = new cry(46, f2);
        final HashMap hashMap47 = new HashMap();
        hashMap47.put(cry47.annotationType(), cry47);
        V = new lxa("aggregatedOnDevicePoseDetectionLogEvent", wa0.A(hashMap47), null);
        final cry cry48 = new cry(47, f2);
        final HashMap hashMap48 = new HashMap();
        hashMap48.put(cry48.annotationType(), cry48);
        W = new lxa("aggregatedOnDeviceSegmentationLogEvent", wa0.A(hashMap48), null);
        final cry cry49 = new cry(42, f2);
        final HashMap hashMap49 = new HashMap();
        hashMap49.put(cry49.annotationType(), cry49);
        X = new lxa("remoteConfigLogEvent", wa0.A(hashMap49), null);
        final cry cry50 = new cry(50, f2);
        final HashMap hashMap50 = new HashMap();
        hashMap50.put(cry50.annotationType(), cry50);
        Y = new lxa("inputImageConstructionLogEvent", wa0.A(hashMap50), null);
        final cry cry51 = new cry(51, f2);
        final HashMap hashMap51 = new HashMap();
        hashMap51.put(cry51.annotationType(), cry51);
        Z = new lxa("leakedHandleEvent", wa0.A(hashMap51), null);
        final cry cry52 = new cry(52, f2);
        final HashMap hashMap52 = new HashMap();
        hashMap52.put(cry52.annotationType(), cry52);
        a0 = new lxa("cameraSourceLogEvent", wa0.A(hashMap52), null);
        final cry cry53 = new cry(53, f2);
        final HashMap hashMap53 = new HashMap();
        hashMap53.put(cry53.annotationType(), cry53);
        b0 = new lxa("imageLabelOptionalModuleLogEvent", wa0.A(hashMap53), null);
        final cry cry54 = new cry(54, f2);
        final HashMap hashMap54 = new HashMap();
        hashMap54.put(cry54.annotationType(), cry54);
        c0 = new lxa("languageIdentificationOptionalModuleLogEvent", wa0.A(hashMap54), null);
        final cry cry55 = new cry(60, f2);
        final HashMap hashMap55 = new HashMap();
        hashMap55.put(cry55.annotationType(), cry55);
        d0 = new lxa("faceDetectionOptionalModuleLogEvent", wa0.A(hashMap55), null);
        final cry cry56 = new cry(55, f2);
        final HashMap hashMap56 = new HashMap();
        hashMap56.put(cry56.annotationType(), cry56);
        e0 = new lxa("nlClassifierOptionalModuleLogEvent", wa0.A(hashMap56), null);
        final cry cry57 = new cry(56, f2);
        final HashMap hashMap57 = new HashMap();
        hashMap57.put(cry57.annotationType(), cry57);
        f0 = new lxa("nlClassifierClientLibraryLogEvent", wa0.A(hashMap57), null);
        final cry cry58 = new cry(57, f2);
        final HashMap hashMap58 = new HashMap();
        hashMap58.put(cry58.annotationType(), cry58);
        g0 = new lxa("accelerationAllowlistLogEvent", wa0.A(hashMap58), null);
    }
    
    public final void a(final Object o, final Object o2) throws IOException {
        final uhz uhz = (uhz)o;
        final c5j c5j = (c5j)o2;
        c5j.a(z6z.b, uhz.a);
        c5j.a(z6z.c, uhz.b);
        c5j.a(z6z.d, null);
        c5j.a(z6z.e, uhz.c);
        c5j.a(z6z.f, null);
        c5j.a(z6z.g, null);
        c5j.a(z6z.h, null);
        c5j.a(z6z.i, null);
        c5j.a(z6z.j, null);
        c5j.a(z6z.k, null);
        c5j.a(z6z.l, uhz.d);
        c5j.a(z6z.m, null);
        c5j.a(z6z.n, null);
        c5j.a(z6z.o, null);
        c5j.a(z6z.p, null);
        c5j.a(z6z.q, null);
        c5j.a(z6z.r, null);
        c5j.a(z6z.s, null);
        c5j.a(z6z.t, null);
        c5j.a(z6z.u, null);
        c5j.a(z6z.v, null);
        c5j.a(z6z.w, null);
        c5j.a(z6z.x, null);
        c5j.a(z6z.y, null);
        c5j.a(z6z.z, null);
        c5j.a(z6z.A, null);
        c5j.a(z6z.B, null);
        c5j.a(z6z.C, null);
        c5j.a(z6z.D, null);
        c5j.a(z6z.E, null);
        c5j.a(z6z.F, null);
        c5j.a(z6z.G, null);
        c5j.a(z6z.H, null);
        c5j.a(z6z.I, null);
        c5j.a(z6z.J, null);
        c5j.a(z6z.K, null);
        c5j.a(z6z.L, null);
        c5j.a(z6z.M, null);
        c5j.a(z6z.N, null);
        c5j.a(z6z.O, null);
        c5j.a(z6z.P, null);
        c5j.a(z6z.Q, null);
        c5j.a(z6z.R, null);
        c5j.a(z6z.S, null);
        c5j.a(z6z.T, null);
        c5j.a(z6z.U, uhz.e);
        c5j.a(z6z.V, null);
        c5j.a(z6z.W, null);
        c5j.a(z6z.X, null);
        c5j.a(z6z.Y, null);
        c5j.a(z6z.Z, null);
        c5j.a(z6z.a0, null);
        c5j.a(z6z.b0, null);
        c5j.a(z6z.c0, null);
        c5j.a(z6z.d0, null);
        c5j.a(z6z.e0, null);
        c5j.a(z6z.f0, null);
        c5j.a(z6z.g0, null);
    }
}
