import java.lang.annotation.Annotation;
import java.io.IOException;
import java.util.HashMap;

// 
// Decompiled by Procyon v0.6.0
// 

public final class zty implements b5j<o6z>
{
    public static final lxa A;
    public static final lxa B;
    public static final lxa C;
    public static final lxa D;
    public static final lxa E;
    public static final lxa F;
    public static final lxa G;
    public static final lxa H;
    public static final lxa I;
    public static final lxa J;
    public static final lxa K;
    public static final lxa L;
    public static final lxa M;
    public static final lxa N;
    public static final lxa O;
    public static final lxa P;
    public static final lxa Q;
    public static final lxa R;
    public static final lxa S;
    public static final lxa T;
    public static final lxa U;
    public static final lxa V;
    public static final lxa W;
    public static final lxa X;
    public static final lxa Y;
    public static final lxa Z;
    public static final zty a;
    public static final lxa a0;
    public static final lxa b;
    public static final lxa b0;
    public static final lxa c;
    public static final lxa c0;
    public static final lxa d;
    public static final lxa d0;
    public static final lxa e;
    public static final lxa e0;
    public static final lxa f;
    public static final lxa f0;
    public static final lxa g;
    public static final lxa h;
    public static final lxa i;
    public static final lxa j;
    public static final lxa k;
    public static final lxa l;
    public static final lxa m;
    public static final lxa n;
    public static final lxa o;
    public static final lxa p;
    public static final lxa q;
    public static final lxa r;
    public static final lxa s;
    public static final lxa t;
    public static final lxa u;
    public static final lxa v;
    public static final lxa w;
    public static final lxa x;
    public static final lxa y;
    public static final lxa z;
    
    static {
        final z000 f2 = z000.F0;
        a = new zty();
        final czz czz = new czz(1, f2);
        final HashMap hashMap = new HashMap();
        hashMap.put(((Annotation)czz).annotationType(), czz);
        b = new lxa("systemInfo", wa0.A(hashMap), null);
        final czz czz2 = new czz(2, f2);
        final HashMap hashMap2 = new HashMap();
        hashMap2.put(((Annotation)czz2).annotationType(), czz2);
        c = new lxa("eventName", wa0.A(hashMap2), null);
        final czz czz3 = new czz(37, f2);
        final HashMap hashMap3 = new HashMap();
        hashMap3.put(((Annotation)czz3).annotationType(), czz3);
        d = new lxa("isThickClient", wa0.A(hashMap3), null);
        final czz czz4 = new czz(3, f2);
        final HashMap hashMap4 = new HashMap();
        hashMap4.put(((Annotation)czz4).annotationType(), czz4);
        e = new lxa("modelDownloadLogEvent", wa0.A(hashMap4), null);
        final czz czz5 = new czz(20, f2);
        final HashMap hashMap5 = new HashMap();
        hashMap5.put(((Annotation)czz5).annotationType(), czz5);
        f = new lxa("customModelLoadLogEvent", wa0.A(hashMap5), null);
        final czz czz6 = new czz(4, f2);
        final HashMap hashMap6 = new HashMap();
        hashMap6.put(((Annotation)czz6).annotationType(), czz6);
        g = new lxa("customModelInferenceLogEvent", wa0.A(hashMap6), null);
        final czz czz7 = new czz(29, f2);
        final HashMap hashMap7 = new HashMap();
        hashMap7.put(((Annotation)czz7).annotationType(), czz7);
        h = new lxa("customModelCreateLogEvent", wa0.A(hashMap7), null);
        final czz czz8 = new czz(5, f2);
        final HashMap hashMap8 = new HashMap();
        hashMap8.put(((Annotation)czz8).annotationType(), czz8);
        i = new lxa("onDeviceFaceDetectionLogEvent", wa0.A(hashMap8), null);
        final czz czz9 = new czz(59, f2);
        final HashMap hashMap9 = new HashMap();
        hashMap9.put(((Annotation)czz9).annotationType(), czz9);
        j = new lxa("onDeviceFaceLoadLogEvent", wa0.A(hashMap9), null);
        final czz czz10 = new czz(6, f2);
        final HashMap hashMap10 = new HashMap();
        hashMap10.put(((Annotation)czz10).annotationType(), czz10);
        k = new lxa("onDeviceTextDetectionLogEvent", wa0.A(hashMap10), null);
        final czz czz11 = new czz(7, f2);
        final HashMap hashMap11 = new HashMap();
        hashMap11.put(((Annotation)czz11).annotationType(), czz11);
        l = new lxa("onDeviceBarcodeDetectionLogEvent", wa0.A(hashMap11), null);
        final czz czz12 = new czz(58, f2);
        final HashMap hashMap12 = new HashMap();
        hashMap12.put(((Annotation)czz12).annotationType(), czz12);
        m = new lxa("onDeviceBarcodeLoadLogEvent", wa0.A(hashMap12), null);
        final czz czz13 = new czz(48, f2);
        final HashMap hashMap13 = new HashMap();
        hashMap13.put(((Annotation)czz13).annotationType(), czz13);
        n = new lxa("onDeviceImageLabelCreateLogEvent", wa0.A(hashMap13), null);
        final czz czz14 = new czz(49, f2);
        final HashMap hashMap14 = new HashMap();
        hashMap14.put(((Annotation)czz14).annotationType(), czz14);
        o = new lxa("onDeviceImageLabelLoadLogEvent", wa0.A(hashMap14), null);
        final czz czz15 = new czz(18, f2);
        final HashMap hashMap15 = new HashMap();
        hashMap15.put(((Annotation)czz15).annotationType(), czz15);
        p = new lxa("onDeviceImageLabelDetectionLogEvent", wa0.A(hashMap15), null);
        final czz czz16 = new czz(26, f2);
        final HashMap hashMap16 = new HashMap();
        hashMap16.put(((Annotation)czz16).annotationType(), czz16);
        q = new lxa("onDeviceObjectCreateLogEvent", wa0.A(hashMap16), null);
        final czz czz17 = new czz(27, f2);
        final HashMap hashMap17 = new HashMap();
        hashMap17.put(((Annotation)czz17).annotationType(), czz17);
        r = new lxa("onDeviceObjectLoadLogEvent", wa0.A(hashMap17), null);
        final czz czz18 = new czz(28, f2);
        final HashMap hashMap18 = new HashMap();
        hashMap18.put(((Annotation)czz18).annotationType(), czz18);
        s = new lxa("onDeviceObjectInferenceLogEvent", wa0.A(hashMap18), null);
        final czz czz19 = new czz(44, f2);
        final HashMap hashMap19 = new HashMap();
        hashMap19.put(((Annotation)czz19).annotationType(), czz19);
        t = new lxa("onDevicePoseDetectionLogEvent", wa0.A(hashMap19), null);
        final czz czz20 = new czz(45, f2);
        final HashMap hashMap20 = new HashMap();
        hashMap20.put(((Annotation)czz20).annotationType(), czz20);
        u = new lxa("onDeviceSegmentationLogEvent", wa0.A(hashMap20), null);
        final czz czz21 = new czz(19, f2);
        final HashMap hashMap21 = new HashMap();
        hashMap21.put(((Annotation)czz21).annotationType(), czz21);
        v = new lxa("onDeviceSmartReplyLogEvent", wa0.A(hashMap21), null);
        final czz czz22 = new czz(21, f2);
        final HashMap hashMap22 = new HashMap();
        hashMap22.put(((Annotation)czz22).annotationType(), czz22);
        w = new lxa("onDeviceLanguageIdentificationLogEvent", wa0.A(hashMap22), null);
        final czz czz23 = new czz(22, f2);
        final HashMap hashMap23 = new HashMap();
        hashMap23.put(((Annotation)czz23).annotationType(), czz23);
        x = new lxa("onDeviceTranslationLogEvent", wa0.A(hashMap23), null);
        final czz czz24 = new czz(8, f2);
        final HashMap hashMap24 = new HashMap();
        hashMap24.put(((Annotation)czz24).annotationType(), czz24);
        y = new lxa("cloudFaceDetectionLogEvent", wa0.A(hashMap24), null);
        final czz czz25 = new czz(9, f2);
        final HashMap hashMap25 = new HashMap();
        hashMap25.put(((Annotation)czz25).annotationType(), czz25);
        z = new lxa("cloudCropHintDetectionLogEvent", wa0.A(hashMap25), null);
        final czz czz26 = new czz(10, f2);
        final HashMap hashMap26 = new HashMap();
        hashMap26.put(((Annotation)czz26).annotationType(), czz26);
        A = new lxa("cloudDocumentTextDetectionLogEvent", wa0.A(hashMap26), null);
        final czz czz27 = new czz(11, f2);
        final HashMap hashMap27 = new HashMap();
        hashMap27.put(((Annotation)czz27).annotationType(), czz27);
        B = new lxa("cloudImagePropertiesDetectionLogEvent", wa0.A(hashMap27), null);
        final czz czz28 = new czz(12, f2);
        final HashMap hashMap28 = new HashMap();
        hashMap28.put(((Annotation)czz28).annotationType(), czz28);
        C = new lxa("cloudImageLabelDetectionLogEvent", wa0.A(hashMap28), null);
        final czz czz29 = new czz(13, f2);
        final HashMap hashMap29 = new HashMap();
        hashMap29.put(((Annotation)czz29).annotationType(), czz29);
        D = new lxa("cloudLandmarkDetectionLogEvent", wa0.A(hashMap29), null);
        final czz czz30 = new czz(14, f2);
        final HashMap hashMap30 = new HashMap();
        hashMap30.put(((Annotation)czz30).annotationType(), czz30);
        E = new lxa("cloudLogoDetectionLogEvent", wa0.A(hashMap30), null);
        final czz czz31 = new czz(15, f2);
        final HashMap hashMap31 = new HashMap();
        hashMap31.put(((Annotation)czz31).annotationType(), czz31);
        F = new lxa("cloudSafeSearchDetectionLogEvent", wa0.A(hashMap31), null);
        final czz czz32 = new czz(16, f2);
        final HashMap hashMap32 = new HashMap();
        hashMap32.put(((Annotation)czz32).annotationType(), czz32);
        G = new lxa("cloudTextDetectionLogEvent", wa0.A(hashMap32), null);
        final czz czz33 = new czz(17, f2);
        final HashMap hashMap33 = new HashMap();
        hashMap33.put(((Annotation)czz33).annotationType(), czz33);
        H = new lxa("cloudWebSearchDetectionLogEvent", wa0.A(hashMap33), null);
        final czz czz34 = new czz(23, f2);
        final HashMap hashMap34 = new HashMap();
        hashMap34.put(((Annotation)czz34).annotationType(), czz34);
        I = new lxa("automlImageLabelingCreateLogEvent", wa0.A(hashMap34), null);
        final czz czz35 = new czz(24, f2);
        final HashMap hashMap35 = new HashMap();
        hashMap35.put(((Annotation)czz35).annotationType(), czz35);
        J = new lxa("automlImageLabelingLoadLogEvent", wa0.A(hashMap35), null);
        final czz czz36 = new czz(25, f2);
        final HashMap hashMap36 = new HashMap();
        hashMap36.put(((Annotation)czz36).annotationType(), czz36);
        K = new lxa("automlImageLabelingInferenceLogEvent", wa0.A(hashMap36), null);
        final czz czz37 = new czz(39, f2);
        final HashMap hashMap37 = new HashMap();
        hashMap37.put(((Annotation)czz37).annotationType(), czz37);
        L = new lxa("isModelDownloadedLogEvent", wa0.A(hashMap37), null);
        final czz czz38 = new czz(40, f2);
        final HashMap hashMap38 = new HashMap();
        hashMap38.put(((Annotation)czz38).annotationType(), czz38);
        M = new lxa("deleteModelLogEvent", wa0.A(hashMap38), null);
        final czz czz39 = new czz(30, f2);
        final HashMap hashMap39 = new HashMap();
        hashMap39.put(((Annotation)czz39).annotationType(), czz39);
        N = new lxa("aggregatedAutomlImageLabelingInferenceLogEvent", wa0.A(hashMap39), null);
        final czz czz40 = new czz(31, f2);
        final HashMap hashMap40 = new HashMap();
        hashMap40.put(((Annotation)czz40).annotationType(), czz40);
        O = new lxa("aggregatedCustomModelInferenceLogEvent", wa0.A(hashMap40), null);
        final czz czz41 = new czz(32, f2);
        final HashMap hashMap41 = new HashMap();
        hashMap41.put(((Annotation)czz41).annotationType(), czz41);
        P = new lxa("aggregatedOnDeviceFaceDetectionLogEvent", wa0.A(hashMap41), null);
        final czz czz42 = new czz(33, f2);
        final HashMap hashMap42 = new HashMap();
        hashMap42.put(((Annotation)czz42).annotationType(), czz42);
        Q = new lxa("aggregatedOnDeviceBarcodeDetectionLogEvent", wa0.A(hashMap42), null);
        final czz czz43 = new czz(34, f2);
        final HashMap hashMap43 = new HashMap();
        hashMap43.put(((Annotation)czz43).annotationType(), czz43);
        R = new lxa("aggregatedOnDeviceImageLabelDetectionLogEvent", wa0.A(hashMap43), null);
        final czz czz44 = new czz(35, f2);
        final HashMap hashMap44 = new HashMap();
        hashMap44.put(((Annotation)czz44).annotationType(), czz44);
        S = new lxa("aggregatedOnDeviceObjectInferenceLogEvent", wa0.A(hashMap44), null);
        final czz czz45 = new czz(36, f2);
        final HashMap hashMap45 = new HashMap();
        hashMap45.put(((Annotation)czz45).annotationType(), czz45);
        T = new lxa("aggregatedOnDeviceTextDetectionLogEvent", wa0.A(hashMap45), null);
        final czz czz46 = new czz(46, f2);
        final HashMap hashMap46 = new HashMap();
        hashMap46.put(((Annotation)czz46).annotationType(), czz46);
        U = new lxa("aggregatedOnDevicePoseDetectionLogEvent", wa0.A(hashMap46), null);
        final czz czz47 = new czz(47, f2);
        final HashMap hashMap47 = new HashMap();
        hashMap47.put(((Annotation)czz47).annotationType(), czz47);
        V = new lxa("aggregatedOnDeviceSegmentationLogEvent", wa0.A(hashMap47), null);
        final czz czz48 = new czz(42, f2);
        final HashMap hashMap48 = new HashMap();
        hashMap48.put(((Annotation)czz48).annotationType(), czz48);
        W = new lxa("remoteConfigLogEvent", wa0.A(hashMap48), null);
        final czz czz49 = new czz(50, f2);
        final HashMap hashMap49 = new HashMap();
        hashMap49.put(((Annotation)czz49).annotationType(), czz49);
        X = new lxa("inputImageConstructionLogEvent", wa0.A(hashMap49), null);
        final czz czz50 = new czz(51, f2);
        final HashMap hashMap50 = new HashMap();
        hashMap50.put(((Annotation)czz50).annotationType(), czz50);
        Y = new lxa("leakedHandleEvent", wa0.A(hashMap50), null);
        final czz czz51 = new czz(52, f2);
        final HashMap hashMap51 = new HashMap();
        hashMap51.put(((Annotation)czz51).annotationType(), czz51);
        Z = new lxa("cameraSourceLogEvent", wa0.A(hashMap51), null);
        final czz czz52 = new czz(53, f2);
        final HashMap hashMap52 = new HashMap();
        hashMap52.put(((Annotation)czz52).annotationType(), czz52);
        a0 = new lxa("imageLabelOptionalModuleLogEvent", wa0.A(hashMap52), null);
        final czz czz53 = new czz(54, f2);
        final HashMap hashMap53 = new HashMap();
        hashMap53.put(((Annotation)czz53).annotationType(), czz53);
        b0 = new lxa("languageIdentificationOptionalModuleLogEvent", wa0.A(hashMap53), null);
        final czz czz54 = new czz(60, f2);
        final HashMap hashMap54 = new HashMap();
        hashMap54.put(((Annotation)czz54).annotationType(), czz54);
        c0 = new lxa("faceDetectionOptionalModuleLogEvent", wa0.A(hashMap54), null);
        final czz czz55 = new czz(55, f2);
        final HashMap hashMap55 = new HashMap();
        hashMap55.put(((Annotation)czz55).annotationType(), czz55);
        d0 = new lxa("nlClassifierOptionalModuleLogEvent", wa0.A(hashMap55), null);
        final czz czz56 = new czz(56, f2);
        final HashMap hashMap56 = new HashMap();
        hashMap56.put(((Annotation)czz56).annotationType(), czz56);
        e0 = new lxa("nlClassifierClientLibraryLogEvent", wa0.A(hashMap56), null);
        final czz czz57 = new czz(57, f2);
        final HashMap hashMap57 = new HashMap();
        hashMap57.put(((Annotation)czz57).annotationType(), czz57);
        f0 = new lxa("accelerationAllowlistLogEvent", wa0.A(hashMap57), null);
    }
    
    public final void a(final Object o, final Object o2) throws IOException {
        final o6z o6z = (o6z)o;
        final c5j c5j = (c5j)o2;
        c5j.a(zty.b, o6z.a);
        c5j.a(zty.c, o6z.b);
        c5j.a(zty.d, null);
        c5j.a(zty.e, null);
        c5j.a(zty.f, null);
        c5j.a(zty.g, null);
        c5j.a(zty.h, null);
        c5j.a(zty.i, null);
        c5j.a(zty.j, null);
        c5j.a(zty.k, null);
        c5j.a(zty.l, null);
        c5j.a(zty.m, null);
        c5j.a(zty.n, null);
        c5j.a(zty.o, null);
        c5j.a(zty.p, null);
        c5j.a(zty.q, null);
        c5j.a(zty.r, null);
        c5j.a(zty.s, null);
        c5j.a(zty.t, null);
        c5j.a(zty.u, null);
        c5j.a(zty.v, null);
        c5j.a(zty.w, null);
        c5j.a(zty.x, null);
        c5j.a(zty.y, null);
        c5j.a(zty.z, null);
        c5j.a(zty.A, null);
        c5j.a(zty.B, null);
        c5j.a(zty.C, null);
        c5j.a(zty.D, null);
        c5j.a(zty.E, null);
        c5j.a(zty.F, null);
        c5j.a(zty.G, null);
        c5j.a(zty.H, null);
        c5j.a(zty.I, null);
        c5j.a(zty.J, null);
        c5j.a(zty.K, null);
        c5j.a(zty.L, null);
        c5j.a(zty.M, null);
        c5j.a(zty.N, null);
        c5j.a(zty.O, null);
        c5j.a(zty.P, null);
        c5j.a(zty.Q, null);
        c5j.a(zty.R, null);
        c5j.a(zty.S, null);
        c5j.a(zty.T, null);
        c5j.a(zty.U, null);
        c5j.a(zty.V, null);
        c5j.a(zty.W, null);
        c5j.a(zty.X, o6z.c);
        c5j.a(zty.Y, null);
        c5j.a(zty.Z, null);
        c5j.a(zty.a0, null);
        c5j.a(zty.b0, null);
        c5j.a(zty.c0, null);
        c5j.a(zty.d0, null);
        c5j.a(zty.e0, null);
        c5j.a(zty.f0, null);
    }
}
